---
output: html_fragment
---

**3a. Reduce personal safety hazard**: Low head dams in particular can pose a drowning risk by creating recirculating flow patterns at their base which can trap victims under water in these “reverse rollers.” In the US, approximately 50 people drown each year at low head dams by this mechanism ([Landers 2021](https://www.asce.org/publications-and-news/civil-engineering-source/civil-engineering-magazine/article/2021/01/engineers-work-to-reduce-drowning-deaths-at-low-head-dams#:~:text=No%20one%20builds%20a%20dam,known%20as%20low%2Dhead%20dams.){target="_blank"}).  

**3b. Reduce failure hazard**: Dam removal may be justified as a proactive step in mitigating the risk of flooding by dam failure. Dam age, operation, and condition are critical when considering risk (Hansen et al. 2020). Approximately 53% of the nation's dams (48,500) are near or beyond their serviceable life expectancy and many were constructed without plans for decommissioning or removal at the conclusion of their serviceable life ([Hansen et al. 2020](https://doi.org/10.1007/s00027-019-0679-3){target="_blank"};  [USACE 2016](https://www.publications.usace.army.mil/Portals/76/Publications/EngineerPamphlets/EP_360-1-23.pdf){target="_blank"}). The national dam safety program classifies dams by hazard potential. A high hazard potential rating indicates that a dam failure would cause probable loss of life and or serious economic damage. Approximately 2,300 dams are rated as high hazard potential and are in deficient condition ([FEMA 2021](https://www.fema.gov/sites/default/files/documents/fema_nsdp-overview-fact-sheet.pdf#:~:text=The%20National%20Inventory%20of%20Dam%20s%20classifies%20approximately,their%20failure%20could%20result%20in%20loss%20of%20life){target="_blank"}; [ASCE 2021](https://infrastructurereportcard.org/wp-content/uploads/2020/12/Dams-2021.pdf){target="_blank"})
