---
output: html_fragment
---

**5a. Promote/maintain a population or community of focal taxa**: Promote/maintain an organism or group of organisms of interest: By fragmenting critical habitats and altering the flow of water and sediment, dams can promote the decline of freshwater organisms, like migratory fish and freshwater mussels ([Bogan 1993](https://doi.org/10.1093/icb/33.6.599), [Limburg & Waldman 2009](https://doi.org/10.1525/bio.2009.59.11.7)). Dam removal can be a critical component of conservation efforts. This may be a particularly salient objective of dam removal when the organism under consideration is afforded protection under the Endangered Species Act or another legal mechanism (e.g., treaty rights) ([Bowman 2002](https://doi.org/10.1641/0006-3568(2002)052[0739:LPODR]2.0.CO;2)).   

**5b. Promote/maintain biodiversity**: Dams have been implicated in the loss of biodiversity in freshwater ecosystems and restoring connectivity through dam removal and retrofit has been identified as a key step for freshwater biodiversity recovery ([Tickner et al. 2020](https://doi.org/10.1093/biosci/biaa002)). 


**5c. Prevent the spread of invasive species, disease, or undesirable hybridization**: the restriction of aquatic organism by dams can be leveraged in conservation scenarios in which increasing river network access of a species or population is undesirable because it would spread disease, promote undesirable hybridization between populations (e.g., farmed and wild salmon), or because the species is invasive (e.g., lamprey in the Great Lakes) ([McLaughlin et al. 2013](https://doi.org/10.1111/faf.12003), [Melles et al. 2015](https://doi.org/10.1007/s10980-014-0114-z)).

**5d. Reduce greenhouse gas emissions**: Reservoirs created by dams can be relatively large sources of greenhouse gas emissions to the atmosphere. In flooding terrestrial soils and vegetation dams can convert land from a carbon dioxide sink to a carbon dioxide source. Dams also concentrate organic matter in their sediments, creating a high demand for oxygen which is consumed in the breakdown of organic matter. When sediments are depleted of oxygen, organisms called methanogens can break down organic matter to produce methane: a potent greenhouse gas which has 28 times the warming potential of carbon dioxide ([Deemer et al. 2016](https://doi.org/10.1093/biosci/biw117)). Dam removal may reduce methane emissions by reducing the frequency of conditions conducive for methane production and emission and by facilitating the establishment of terrestrial vegetation carbon dioxide sink. 

**5e. Maintain or improve water quality**: Removing a dam alters the physical and chemical characteristics of the aquatic ecosystem which control the dispersal of sediment and toxins, oxygen dynamics, nutrient availability, and the risk of harmful algal blooms ([Stanley and Doyle 2003](
https://doi.org/10.1890/1540-9295(2003)001[0015:TOTEEO]2.0.CO;2); [Oliver et al. 2014](
https://doi.org/10.1016/j.jhydrol.2014.06.025)).  

**5f. Reduce stream geomorphic degradation**: Dam removal can release impounded water and sediment downstream, which drives context-dependent changes in geomorphology, including triggering a years-long pattern of reservoir erosion and downstream deposition that has hydroecological effects ([Major et al. 2017](https://doi.org/10.1002/9781118971437.ch13)). In a system previously destabilized by sediment trapping and experiencing migrating headcuts, restoring sediment connectivity can avoid downstream bank failures which would have occurred through channel incision. 
