---
output: html_fragment
---

<style type="text/css">
  h1{
  font-size: 2.5em;
}
</style>

# Estimated landscape greenhouse gas balance

Landscape greenhouse gas balance (here defined as greenhouse gas balance from the reservoir impounded area) is generally estimated using measurements from similar systems. Most estimates of reservoir greenhouse gas emissions quantify CO~2~ and CH~4~ emissions only, as nitrous oxide (N~2~O) is responsible for an average of only 4% of the radiative forcing from reservoirs ([Deemer et al. 2016](https://doi.org/10.1093/biosci/biw117){target="_blank"}). Tools like [g-res](https://131.datatrium.com/fmi/webd/G-res%20Tool?script=ChoiceWebPage&param=Grestool&homeurl=https://g-res.hydropower.org){target="_blank"} are useful for estimating greenhouse gas emissions attributable to the reservoir while it is impounded. To estimate the change in landscape greenhouse gas balance following dam removal, many other gas sources and sinks in the reservoir footprint should be accounted for including: soil CO~2~ emissions, river CO~2~ emissions, tree CO~2~ uptake, soil CH~4~ uptake, river CH~4~ emissions, tree CH~4~ emissions, as well as the transitional emissions from decomposition of newly exposed organic matter in the former reservoir sediments.

For hydropower dams, carbon intensity–CO~2~-eq emissions per unit electricity generated–may be an appropriate method important for evaluating the environmental impact of hydropower generation at a particular dam.

## Data requirements/sources
Data concerning characteristics of the reservoir relevant for estimating greenhouse gas emissions (e.g., trophic status), relevant gas balance estimates from similar systems, component emissions/uptake estimates from similar systems

## Citations
([Prairie et al. 2018](https://doi.org/10.1007/s10021-017-0198-9){target="_blank"}; [Almeida et al. 2019](https://doi.org/10.1038/s41467-019-12179-5){target="_blank"})