---
output: html_fragment
---

<style type="text/css">
  h1{
  font-size: 2.5em;
}
</style>

# Connectivity methods

Numerous connectivity methods are available to describe potential changes in species access to a river network with barrier addition or removal (see [McKay et al. 2017](https://doi.org/10.1002/rra.3021), [Jumani et al. 2020](https://doi.org/10.1088/1748-9326/abcb37))

Note that flow intermittency may be an important consideration in calculating connectivity, particularly in dryland rivers ([Marshall et al. 2021](https://doi.org/10.3389/fenvs.2021.671556))

Key distinctions among methods:

* Passability of barriers parameterized as binary vs. continuous
* All reaches considered suitable habitat vs.suitable reaches determined by a model or historic data
* Spatial relationship among habitats required life cycle completion (e.g., metrics for anadromous organisms quantify connectivity to the ocean while metrics for resident or potamodromous organisms may not)


## Data requirements/sources
Geospatial model of the river network (e.g., [NHDPlus](https://www.usgs.gov/national-hydrography/nhdplus-high-resolutio)), passability of barriers (see [Kemp & O'Hanley 2010](https://doi.org/10.1111/j.1365-2400.2010.00751.x)), and suitable habitat within the network

## Citations
([Kuby et al. 2005](https://doi.org/10.1016/j.advwatres.2004.12.015); [Kocovsky et al. 2009](https://doi.org/10.1002/rra.1094), [Null et al. 2014](http://dx.doi.org/10.1016/j.jenvman.2014.01.024); [Sethi et al. 2017](https://doi.org/10.1007/s10980-017-0571-2); [McKay et al. 2017](https://doi.org/10.1002/rra.3021))